import random
from src.models import Deal
from src.services.category_classifier import classify

_TEMPLATES: dict[str, list[str]] = {
    "console": [
        "fim de semana que vem tem desculpa pra não sair de casa 🎮",
        "esse aqui some rápido quando aparece assim ⚡",
        "tava na lista de desejos de muita gente faz tempo 👀",
        "quem joga sabe que esse preço não aparece sempre 🔥",
        "presente de aniversário praticamente se escolhendo sozinho 🎁",
        "pra quem tá esperando o momento certo. chegou 🫡",
    ],
    "smartphone": [
        "câmera, bateria e desempenho por esse valor? bora 📱",
        "um dos melhores custo-benefício que apareceu por aqui 🔥",
        "tava na lista de desejos de muita gente faz tempo 👀",
        "esse aqui some antes de você terminar de pensar ⚡",
        "upgrade que você vai sentir no primeiro dia de uso 😍",
        "raro aparecer nessa faixa de preço com essa qualidade 🫡",
    ],
    "notebook": [
        "trabalho, faculdade ou diversão. esse resolve os três 💻",
        "um dos melhores custo-benefício que apareceu por aqui 🔥",
        "tava na lista de desejos de muita gente faz tempo 👀",
        "pra quem tá precisando de upgrade e esperando a hora certa ⚡",
        "desempenho de respeito por um preço que faz sentido 😌",
        "esse aqui some rápido quando aparece assim 🫡",
    ],
    "eletronico": [
        "tava na lista de desejos de muita gente 👀",
        "esse aqui some rápido quando aparece assim ⚡",
        "raro aparecer nessa faixa de preço com essa qualidade 🔥",
        "um dos melhores preços que apareceu por aqui 🫡",
        "pra quem tá esperando o momento certo. chegou 😌",
        "quem conhece o produto sabe que esse preço não dura 😬",
    ],
    "kit_intimo": [
        "dessas coisas que a gente lembra que precisa só quando tá sem 😅",
        "kit completo e ainda sobra dinheiro no bolso 😌",
        "pra repor o estoque sem culpa nenhuma 😂",
        "quem nunca deixou essa necessidade acumular mais do que devia? 🙋",
        "barato, necessário e você nem vai perceber que gastou 👌",
        "compra e esquece por um bom tempo 🛒",
    ],
    "calcado": [
        "par novo e o bolso agradece 👟",
        "daqueles que você usa até não poder mais 😌",
        "calçado que vai servir em várias ocasiões 🎯",
        "um dos melhores preços que apareceu pra esse modelo 🔥",
        "pra quem tá de olho em renovar o calçado faz tempo 👀",
        "conforto e estilo por um preço que faz sentido 😍",
    ],
    "roupa": [
        "roupa boa barata é difícil. quando aparece, não fica 👕",
        "atualiza o guarda-roupa sem fazer besteira no cartão ✅",
        "tem peça que você compra e usa anos. essa parece uma 👀",
        "visual novo sem dor no bolso 😍",
        "versátil, combina com tudo que você já tem 🎯",
        "pra quem tá de olho em renovar o guarda-roupa faz tempo 🛍️",
    ],
    "casa": [
        "casa organizada começa por uma compra assim 🏠",
        "um daqueles itens que a diferença você sente no primeiro dia 😍",
        "pra quem tá montando ou reformando. hora certa 🔨",
        "lembra aquela coisa que precisava trocar faz tempo? então 👇",
        "esse tipo de compra você não arrepende 🤌",
        "utilidade do dia a dia por um preço que faz sentido 💡",
        "quem mora sozinho sabe a falta que faz 🙋",
    ],
    "bebida_alcoolica": [
        "próximo churrasco ou happy hour já tem o que servir 🍺",
        "pra estocar antes do próximo encontro 😏",
        "presente fácil e certeiro pra quem curte a boa 🎁",
        "rótulo bom por esse preço vale guardar 👀",
        "pra ter em casa e não depender de loja na hora h 🛒",
        "quem aprecia sabe que esse preço não aparece sempre 🍷",
    ],
    "suplemento": [
        "desculpa de não bater a meta de proteína acabou 💪",
        "pra quem leva a dieta a sério e não quer pagar caro 🎯",
        "estoque o mês sem sentir no bolso 📦",
        "rendimento e recuperação por um preço que faz sentido 🏋️",
        "pra quem treina e sabe o quanto isso faz diferença 🔥",
        "compra agora, agradece no treino de amanhã 😌",
    ],
    "alimento": [
        "pra estocar e não ficar na mão 🛒",
        "básico da despensa que tá barato agora 👌",
        "dessas compras que você faz e fica feliz por semanas 😋",
        "pra quem gosta de ter em casa e nunca deixar faltar 🏠",
        "compra agora e agradece daqui a três semanas 🙏",
        "quem faz mercado sabe reconhecer uma boa quando vê 🧐",
    ],
    "perfume": [
        "cheiro bom por esse preço não aparece sempre 😮",
        "aquele presente que todo mundo fica perguntando de onde veio 👀",
        "pra chegar num ambiente e deixar rastro 😏",
        "bom demais pra usar só em ocasiões especiais 🌸",
        "presente praticamente pronto. é só embrulhar 🎁",
        "quem gosta de perfume sabe que esse preço não volta fácil 🙏",
    ],
    "higiene": [
        "básico que nunca pode faltar 🛒",
        "daquelas marcas que você já conhece e confia 👍",
        "pra estocar o que já usa e não ser pego desprevenido 📦",
        "rotina do dia a dia por um preço que faz sentido 😌",
        "qualidade de sempre, preço melhor do que o de sempre ✅",
        "é o tipo de coisa que você vai usar de qualquer jeito 🤌",
    ],
    "ferramenta": [
        "quem tem em casa resolve qualquer coisa 🔧",
        "aquela tarefa parada vai sair hoje 💪",
        "ferramenta boa dura anos 🛠️",
        "pra quem fica chamando ajuda pra tudo. chegou a hora 😂",
        "compra uma vez, usa pra sempre 🤝",
        "daqueles que você não pensa duas vezes depois que tem ✅",
    ],
    "livro": [
        "esse tava na lista de muita gente faz tempo 📚",
        "pra quem procrastina a leitura por conta do preço. acabou a desculpa 😌",
        "leitura boa não precisa custar caro 📖",
        "daqueles que você lê e indica pra todo mundo 🔥",
        "coleção que vale muito a pena completar agora 👀",
        "presente certeiro pra quem gosta de ler 🎁",
    ],
    "brinquedo": [
        "presente resolvido sem dor de cabeça 🎁",
        "criança não esquece de presente assim 🥹",
        "o tipo de coisa que ocupa a criançada por horas 😂",
        "pra quem tá com aniversário chegando e ainda não comprou nada 👀",
        "clássico que nunca decepciona 🎉",
        "diversão garantida e ainda no orçamento 🎠",
    ],
    "esporte": [
        "desculpa de não treinar acabou 💪",
        "quem fica adiando a academia vai entender 😅",
        "pra quem prefere treinar em casa e nunca achou a hora. essa é a hora 🏋️",
        "equipamento bom faz diferença a longo prazo 📈",
        "meta de começar o treino finalmente vai sair do papel 🔥",
        "investe no corpo hoje, colhe nos próximos anos 🙏",
    ],
    "geral": [
        "um dos melhores preços que apareceu por aqui 👀",
        "desses que some antes de você terminar de pensar ⚡",
        "se tava esperando o momento certo, chegou 🫡",
        "raramente aparece assim. vale conferir 🔥",
        "pra quem conhece o produto, sabe que esse preço não dura 😬",
        "não é toda semana que aparece uma assim 🎯",
    ],
}


def generate(deal: Deal) -> str:
    category = classify(deal)
    options = _TEMPLATES.get(category, _TEMPLATES["geral"])
    return random.choice(options)
